### ISSUE TITLE
Unable to run the game

### ISSUE THREAD

**Issue by janman13** [OpenSWE1R/openswe1r#147]
Hey everyone!
I didn't manage to run the game... 
I downloaded it from git (and all the libraries) and then build as in the readme. Then I copied the  "gnome/" folder from the iso, as the "getting started" in the wiki specifies, and try to run it, but the game crashes, with the following error message:

```
lpText 0x4B7E44 ('Error:  Please reinstall program from CD-ROM.
       Press OK to exit to desktop.')
lpCaption 0x4B7E98 ('BAD INSTALL')
```

When I try to install it from the CD via wine, and then run the openswe1r binary from the installed folder, I get  asked for a CD:

```
hWnd 0x14D
lpText 0xC07FFD18 ('Error:  Please insert CD-ROM 'racer100_0' into drive. Press OK to continue or CANCEL to exit to desktop.')
lpCaption 0x4B7DA4 ('CD ERROR')
```

Any ideas?

Note: the version of the ISO is Version 1.0 4/27/99. My distro is Ubuntu 17.10. Unicorn Engine 1.0.1, SDL 2.0, GLEW 2.1, OpenAL 1.1

**Comment by JayFoxRox** [comment]
Can you go into your build folder and run `tree` then post the output here?

**Comment by janman13** [comment]
The objdump:

> Time/Date		Thu Apr 29 05:12:14 1999
22c2781b3cf606b7a093ec5a39ac2af5  swep1rcr.exe

The tree: 
[tree.txt](https://github.com/OpenSWE1R/openswe1r/files/1977852/tree.txt)

the disc is in English, US version.

**Comment by JayFoxRox** [comment]
The files must be in all lowercase. This was the case for my disc.
I assumed this was true for all discs. Unfortunately the installer does rename them to "somtimEsMixedCase.EXT"

Looks like your disc is not in lowercase. Either use a tool to turn the filenames to lowercase, or write a patch for #43 .

This is hopefully the only issue with your copy of the game.
If there are more problems use this issue @janman13 .

I'll close this issue now as it's a known issue.
