### ISSUE TITLE
Unicorn-Engine error of type 19 (EIP: 0x00424358)

### ISSUE THREAD

**Issue by adolfintel** [OpenSWE1R/openswe1r#151]
I tried building OpenSWE1R using the build instructions on the wiki but I'm getting an error when running.

## The steps I followed:
* Installed MSYS2
* Opened MSYS2 - MinGW64
* pacman -Syu
* Installed git, cmake, gcc, make, python2, etc. (I had to do this "interactively" since the wiki doesn't have a clear list of the packages needed to build it)
* Built Unicorn engine and installed the package
* Cloned openswe1r repository (commit ef8ca30b831a4cc967b3fd927a1aaf559c490c38)
* Built openswe1r
* Copied openswe1r.exe and the required DLLs to the game's folder
* Ran openswe1r.exe, a white window briefly popped up before the error appeared (compatibility flags and permissions had no effect)

## System configuration:
* Windows 10 x64 1803
* i7 8700k (virtualization enabled)
* GTX 1080 (no issues with OpenGL driver)

## Game version:
* GOG (hotfix2)
* Also tested the original game with the official patch (same result)

## Files
[Log](https://github.com/OpenSWE1R/openswe1r/files/1987402/log.txt)

I tried looking up the error but I can't find anything.

**Comment by JayFoxRox** [comment]
I can reproduce the issue on Linux (`USE_VM` enabled) running PR #150 .
I'll run the "hotfix" and "hotfix2" through a diff and document what I see. Keep an eye on #142

**Comment by adolfintel** [comment]
Is this specific of hotfix2? Because I have the original game files too and I'm getting the same error there (unless the install is somehow corrupt)

**Comment by JayFoxRox** [comment]
I've tried (each with #150 ):
* gog.com 1.0: working 
* gog.com 1.0 hotfix: working
* gog.com 1.0 hotfix2: broken, same error as described in issue title

Are you sure it's the same error when using another version of the game? If not, please open a new issue (as I already have a hunch about what's going on).

**Comment by adolfintel** [comment]
I guess the crack I'm using has something in common with the hotfix 2 then. It was downloaded a good 18 years ago 😂

**Comment by adolfintel** [comment]
Shit, confirmed, I tried using the original exe and the game starts

**Comment by JayFoxRox** [comment]
Please check if #153 resolves *this* issue for you.
