### ISSUE TITLE
Game starts to run and then exits

### ISSUE THREAD

**Issue by jordan4302** [OpenSWE1R/openswe1r#157]
OpenSWE1R starts and it opens a black game window, but then then it exits before it gets any further. I have attached a txt file with the console output. I'm using Ubuntu 18.04 LTS on a VMware Fusion virtual machine. I did follow the instructions to get the game files from the original game disc. I apologize in advance if this turns out to just be me doing something wrong.

[console output.txt](https://github.com/OpenSWE1R/openswe1r/files/2040588/console.output.txt)

**Comment by JayFoxRox** [comment]
Thanks for the report!

Can you please state which version of the repository you are using? Can be checked with `git rev-parse HEAD`.
Also, which folder did you install the game to? And please provide the md5sum for the game binary: `md5sum swep1rcr.exe`

From the look of it, this looks like an incompatibility of OpenSWE1R with the CD check in the game version you are using ("Game version: Retail, English").
I'll try to reproduce the issue locally later.

There doesn't seem to be any issues with filepaths / file copying.

**Comment by JayFoxRox** [comment]
There have been changes to the CD check since then. Please try with the latest revision (89d1820236ed77c5475996c5f218c7f340fd93d9 at the time of writing).
If the issue persists, I'll look into it.
