### ISSUE TITLE
Build correctly in manjaro but hangs at startup when music is playing

### ISSUE THREAD

**Issue by darkstar252** [OpenSWE1R/openswe1r#179]
Okay the program builds okay ,but when the menu screen appears in the time to play music, the program hangs itself doesn't quit with mouse doesn't start new tournament or new practice session, or doesn't show settings :(

**Comment by JayFoxRox** [comment]
> but when the menu screen appears in the time to play music,

The music streaming thread is not handled, so the music will repeat a small buffer. See #7 and #47 .

>  the program hangs itself

This should not happen (until RAM is filled up - which is a major issue in OpenSWE1R, see #14 ).

I believe you are misinterpreting what's happening: If you can still move the mouse or hear audio, then OpenSWE1R doesn't hang.

> doesn't quit with mouse doesn't start new tournament or new practice session, or doesn't show settings

The mouse buttons are not mapped (see #31 ). Use the mouse to move the cursor, but use space or enter to select entries. This is also how the game behaves without DirectInput mice.

**Comment by darkstar252** [comment]
Thanks for the explanation. The projects seems to be good. But mmmm ... i think it's slow and it's a WIP. But it's nice thanks for the info :)

**Comment by JayFoxRox** [comment]
> But mmmm ... i think it's slow

You can use CPU virtualization and it will run full-speed: https://github.com/OpenSWE1R/openswe1r/wiki/Build-Options

I also have work-in-progress branches for using the CPU natively without virtualization (https://github.com/JayFoxRox/openswe1r/pull/43), also more work on Windows virtualization (WHPX and HAXM in https://github.com/JayFoxRox/openswe1r/pull/42).
However, this is low priority to me, as I don't use Windows myself.

Most work has also gone into profiling and identifying code which will have the biggest performance impact: https://github.com/OpenSWE1R/openswe1r/wiki/Debugging-Tips#example-identifying-performance-bottlenecks (see #3 ).
Such code is typically part of https://github.com/OpenSWE1R/swe1r-re but hasn't been integrated here at this point (see #8 ).

> and it's a WIP

Yes. Patches welcome.

Most work right now is focused on stability / memory usage. This is necessary as I'm porting the game to original Xbox, which only has 64MiB of RAM.

---

Looks like all questions have been answered / game doesn't hang (so the original issue is "solved").

Closed.
