### ISSUE TITLE
uc_kvm_loader.asm refers to bad MIT LICENSE file

### ISSUE THREAD

**Issue by JayFoxRox** [OpenSWE1R/openswe1r#76]
It would be best if this file could be relicensed to GPL to avoid having to ship with a copy of the MIT license (CC @phire ). As it stands, OpenSWE1R does not ship with a copy of the MIT license, making this a copyright violation.

Including the MIT or getting permission might not even be necessary though because the file is substentially different from the original file. It essentially has been rewritten entirely. Chances are we can just relicense it to GPL.

Eitherway: This requires changes or the file should be removed.
Also related to #9 as we should get rid of this bios anyway.

**Comment by phire** [comment]
I give permission to relicense my work in uc_kvm_loader.asm however you like.
